version: "3.8"
services:
  java:
    build:
      context: ./
    ports:
      - "8080:8080"
    container_name: java
    links:
      - mongo
    depends_on:
      - mongo
    networks:
      - shared-net
    environment:
      SECRET: sdagf443a2cdxf3f23f44325d43

  mongo:
    image: 'mongo'
    ports:
      - 27017:27017
    container_name: mongo
    networks:
      - shared-net

networks:
  shared-net:
    driver: bridge