spring:
    mvc:
        converters:
            preferred-json-mapper: gson
    data:
        mongodb:
            database: test_one
            port: 27017
            host: mongo

jwt:
    expiration-time: 300000000